version: '3.8'

services:
  # フロントエンド（静的ファイル配信用）
  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/usr/share/nginx/html
    depends_on:
      - backend
    restart: unless-stopped

  # バックエンドAPI
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.production
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - SECRET_KEY=${SECRET_KEY}
    env_file:
      - .env.production
    depends_on:
      - db
    restart: unless-stopped
    # 本番環境ではポートを外部に公開しない（nginxを通してアクセス）

  # データベース
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - .env.production
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
      - ./backup:/backup
    restart: unless-stopped
    # セキュリティのためポートを外部公開しない

volumes:
  postgres_data_prod: